package entidades;
// Generated 03-31-2022 02:20:20 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category",catalog="blog"
)
public class Category  implements java.io.Serializable {


     private Integer idCategory;
     private String name;
     private String detail;
     private List<Post> posts = new ArrayList<>();

    public Category() {
    }

    public Category(String name, String detail, List<Post> posts) {
       this.name = name;
       this.detail = detail;
       this.posts = posts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCategory", unique=true, nullable=false)
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="detail", length=250)
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }

   @OneToMany(fetch=FetchType.LAZY, mappedBy="category", cascade = CascadeType.ALL)
    public List<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(List<Post> posts) {
        this.posts = posts;
    }




}


